export const GET_USER_LIST_REQUEST = "GET_USER_LIST_REQUEST";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const GET_USER_LIST_FAIL = "GET_USER_LIST_FAIL";

export const DELETE_USER_LIST_REQUEST = "DELETE_USER_LIST_REQUEST";
export const DELETE_USER_LIST_SUCCESS = "DELETE_USER_LIST_SUCCESS";
export const DELETE_USER_LIST_FAIL = "DELETE_USER_LIST_FAIL";
export const DELETE_USER_LIST_RESET = "DELETE_USER_LIST_RESET";

export const GET_ARTIST_LIST_REQUEST = "GET_ARTIST_LIST_REQUEST";
export const GET_ARTIST_LIST_SUCCESS = "GET_ARTIST_LIST_SUCCESS";
export const GET_ARTIST_LIST_FAIL = "GET_ARTIST_LIST_FAIL";

export const DELETE_ARTIST_LIST_REQUEST = "DELETE_ARTIST_LIST_REQUEST";
export const DELETE_ARTIST_LIST_SUCCESS = "DELETE_ARTIST_LIST_SUCCESS";
export const DELETE_ARTIST_LIST_FAIL = "DELETE_ARTIST_LIST_FAIL";
export const DELETE_ARTIST_LIST_RESET = "DELETE_ARTIST_LIST_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
