export const GET_USER_LIST_REQUEST = 'GET_USER_LIST_REQUEST';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAIL = 'GET_USER_LIST_FAIL';

export const UPDATE_USER_LIST_REQUEST = 'UPDATE_USER_LIST_REQUEST';
export const UPDATE_USER_LIST_SUCCESS = 'UPDATE_USER_LIST_SUCCESS';
export const UPDATE_USER_LIST_FAIL = 'UPDATE_USER_LIST_FAIL';

export const GET_ARTIST_LIST_REQUEST = 'GET_ARTIST_LIST_REQUEST';
export const GET_ARTIST_LIST_SUCCESS = 'GET_ARTIST_LIST_SUCCESS';
export const GET_ARTIST_LIST_FAIL = 'GET_ARTIST_LIST_FAIL';

export const UPDATE_ARTIST_LIST_REQUEST = 'UPDATE_ARTIST_LIST_REQUEST';
export const UPDATE_ARTIST_LIST_SUCCESS = 'UPDATE_ARTIST_LIST_SUCCESS';
export const UPDATE_ARTIST_LIST_FAIL = 'UPDATE_ARTIST_LIST_FAIL';


export const CLEAR_ERRORS = 'CLEAR_ERRORS';