export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const ARTIST_LOGIN_REQUEST = 'ARTIST_LOGIN_REQUEST';
export const ARTIST_LOGIN_FAIL = 'ARTIST_LOGIN_FAIL';
export const ARTIST_LOGIN_SUCCESS = 'ARTIST_LOGIN_SUCCESS';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

export const ARTIST_REGISTER_REQUEST = 'ARTIST_REGISTER_REQUEST';
export const ARTIST_REGISTER_FAIL = 'ARTIST_REGISTER_FAIL';
export const ARTIST_REGISTER_SUCCESS = 'ARTIST_REGISTER_SUCCESS';

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';

export const LOAD_ARTIST_REQUEST = 'LOAD_ARTIST_REQUEST';
export const LOAD_ARTIST_FAIL = 'LOAD_ARTIST_FAIL';
export const LOAD_ARTIST_SUCCESS = 'LOAD_ARTIST_SUCCESS';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const ARTIST_UPDATE_REQUEST = 'ARTIST_UPDATE_REQUEST';
export const ARTIST_UPDATE_FAIL = 'ARTIST_UPDATE_FAIL';
export const ARTIST_UPDATE_SUCCESS = 'ARTIST_UPDATE_SUCCESS';
export const ARTIST_UPDATE_RESET = 'ARTIST_UPDATE_RESET';

export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST';
export const USER_UPDATE_PASSWORD_FAIL = 'USER_UPDATE_PASSWORD_FAIL';
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS';
export const USER_UPDATE_PASSWORD_RESET = 'USER_UPDATE_PASSWORD_RESET';

export const ARTIST_UPDATE_PASSWORD_REQUEST = 'ARTIST_UPDATE_PASSWORD_REQUEST';
export const ARTIST_UPDATE_PASSWORD_FAIL = 'ARTIST_UPDATE_PASSWORD_FAIL';
export const ARTIST_UPDATE_PASSWORD_SUCCESS = 'ARTIST_UPDATE_PASSWORD_SUCCESS';
export const ARTIST_UPDATE_PASSWORD_RESET = 'ARTIST_UPDATE_PASSWORD_RESET';



export const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST';
export const USER_FORGOT_PASSWORD_FAIL = 'USER_FORGOT_PASSWORD_FAIL';
export const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS';
export const USER_FORGOT_PASSWORD_RESET = 'USER_FORGOT_PASSWORD_RESET';


export const ARTIST_FORGOT_PASSWORD_REQUEST = 'ARTIST_FORGOT_PASSWORD_REQUEST';
export const ARTIST_FORGOT_PASSWORD_FAIL = 'ARTIST_FORGOT_PASSWORD_FAIL';
export const ARTIST_FORGOT_PASSWORD_SUCCESS = 'ARTIST_FORGOT_PASSWORD_SUCCESS';
export const ARTIST_FORGOT_PASSWORD_RESET = 'ARTIST_FORGOT_PASSWORD_RESET';

export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST';
export const USER_RESET_PASSWORD_FAIL = 'USER_RESET_PASSWORD_FAIL';
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS';
export const USER_RESET_PASSWORD_RESET = 'USER_RESET_PASSWORD_RESET';

export const ARTIST_RESET_PASSWORD_REQUEST = 'ARTIST_RESET_PASSWORD_REQUEST';
export const ARTIST_RESET_PASSWORD_FAIL = 'ARTIST_RESET_PASSWORD_FAIL';
export const ARTIST_RESET_PASSWORD_SUCCESS = 'ARTIST_RESET_PASSWORD_SUCCESS';
export const ARTIST_RESET_PASSWORD_RESET = 'ARTIST_RESET_PASSWORD_RESET';

export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';


export const LOGOUT_ARTIST_FAIL = 'LOGOUT_ARTIST_FAIL';
export const LOGOUT_ARTIST_SUCCESS = 'LOGOUT_ARTIST_SUCCESS';