export const ADD_TO_WISHLIST_REQUEST = 'ADD_TO_WISHLIST_REQUEST';
export const ADD_TO_WISHLIST_FAIL = 'ADD_TO_WISHLIST_FAIL';
export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_WISHLIST_SUCCESS';
export const CLEAR_ERRORS ='CLEAR_ERRORS';

export const MY_WISHLIST_REQUEST = 'MY_WISHLIST_REQUEST';
export const MY_WISHLIST_FAIL = 'MY_WISHLIST_FAIL';
export const MY_WISHLIST_SUCCESS = 'MY_WISHLIST_SUCCESS';